### ISSUE TITLE
SIGABRT when I start training

### ISSUE THREAD

**Issue by jayavanth** [facebookresearch/wav2letter#124]
OS: Ubuntu 18.04
gcc: 7.3.0-27
CUDA: 10

```
$ /home/jay/wav2letter/build/Train --flagsfile /home/jay/wav2letter/tutorials/1-librispeech_clean/train.cfg
F0104 11:36:34.712591 31748 Train.cpp:120] Usage: 
 /home/jay/wav2letter/build/Train train [flags]
 or  continue [directory] [flags]
 or /home/jay/wav2letter/build/Train fork [directory/model] [flags]
*** Check failure stack trace: ***
    @     0x7fb06ef510cd  google::LogMessage::Fail()
    @     0x7fb06ef52f33  google::LogMessage::SendToLog()
    @     0x7fb06ef50c28  google::LogMessage::Flush()
    @     0x7fb06ef53999  google::LogMessageFatal::~LogMessageFatal()
    @     0x5593d141ffe5  (unknown)
    @     0x7faff7340b97  __libc_start_main
    @     0x5593d14522ea  (unknown)
[1]    31748 abort (core dumped)  /home/jay/wav2letter/build/Train --flagsfile
```

I ran it through gdb and I get this:
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by vineelpratap** [comment]
Looks like you have not specified the `mode`  for training. 

It should be 
```
.../Train train --flagsfile /home/jay/wav2letter/tutorials/1-librispeech_clean/train.cfg
```

**Comment by jayavanth** [comment]
Thanks. I changed it to `/home/jay/wav2letter/build/Train train --flagsfile /home/jay/wav2letter/tutorials/1-librispeech_clean/train.cfg`
and my train.cfg looks like this: https://pastebin.com/xbRGYKDk

Now I'm getting a SIGSEGV

`Thread 1 "Train" received signal SIGSEGV, Segmentation fault.
0x00007ffff5a1fc17 in mkl_dft_bless_node_omp () from /home/jay/intel/mkl/lib/intel64/libmkl_gnu_thread.so`

I see that a config file has been generated in the `rundir`

**Comment by vineelpratap** [comment]
We have not seen this happen. Do you have the backtrace from `gdb` ?

Training config looks good to me.

**Comment by jayavanth** [comment]
Yes. Seems to originate from this call `fftPlan_ = fftw_plan_dft_r2c_1d(nFFt, inFftBuf_.data(), (fftw_complex*)outFftBuf_.data(), FFTW_MEASURE);`
```
(gdb) bt
#0  0x00007ffff5a1fc17 in mkl_dft_bless_node_omp () from /home/jay/intel/mkl/lib/intel64/libmkl_gnu_thread.so
#1  0x00007ffff6b3a9d7 in DftiCreateDescriptor_d_1d () from /home/jay/intel/mkl/lib/intel64/libmkl_gf_lp64.so
#2  0x00007ffff6b41170 in fftw_plan_guru64_dft_r2c () from /home/jay/intel/mkl/lib/intel64/libmkl_gf_lp64.so
#3  0x00007ffff6b3fe6b in fftw_plan_dft_r2c () from /home/jay/intel/mkl/lib/intel64/libmkl_gf_lp64.so
#4  0x00007ffff6b3feab in fftw_plan_dft_r2c_1d () from /home/jay/intel/mkl/lib/intel64/libmkl_gf_lp64.so
#5  0x000055555581679b in speech::PowerSpectrum<float>::PowerSpectrum (this=0x555555e08c00 <w2l::(anonymous namespace)::getMfsc()::mfsc>, params=...)
    at /home/jay/wav2letter/src/feature/PowerSpectrum.cpp:30
#6  0x0000555555814660 in speech::Mfsc<float>::Mfsc (this=0x555555e08c00 <w2l::(anonymous namespace)::getMfsc()::mfsc>, params=...)
    at /home/jay/wav2letter/src/feature/Mfsc.cpp:30
#7  0x00005555558082b6 in w2l::(anonymous namespace)::getMfsc () at /home/jay/wav2letter/src/data/Featurize.cpp:34
#8  0x00005555558089be in w2l::featurize (data=std::vector of length 4, capacity 4 = {...}, dicts=std::unordered_map with 1 element = {...})
    at /home/jay/wav2letter/src/data/Featurize.cpp:89
#9  0x00005555557e7a98 in w2l::W2lDataset::getFeatureData (this=0x555571e7b5e0, idx=0) at /home/jay/wav2letter/src/data/W2lDataset.cpp:76
#10 0x00005555557e7c60 in w2l::W2lDataset::getFeatureDataAndPrefetch (this=0x555571e7b5e0, idx=0) at /home/jay/wav2letter/src/data/W2lDataset.cpp:87
#11 0x00005555557e7567 in w2l::W2lDataset::get (this=0x555571e7b5e0, idx=0) at /home/jay/wav2letter/src/data/W2lDataset.cpp:48
#12 0x00005555555a85d4 in fl::detail::DatasetIterator<fl::Dataset, std::vector<af::array, std::allocator<af::array> > >::operator* (this=0x7fffffffcec0)
    at /usr/local/include/flashlight/dataset/DatasetIterator.h:48
#13 0x0000555555592de4 in <lambda(std::shared_ptr<fl::Module>, std::shared_ptr<w2l::SequenceCriterion>, std::shared_ptr<w2l::W2lDataset>, fl::FirstOrderOptimizer&, fl::FirstOrderOptimizer&, bool, int)>::operator()(std::shared_ptr<fl::Module>, std::shared_ptr<w2l::SequenceCriterion>, std::shared_ptr<w2l::W2lDataset>, fl::FirstOrderOptimizer &, fl::FirstOrderOptimizer &, bool, int) const (__closure=0x7fffffffd360, ntwrk=std::shared_ptr<fl::Module> (use count 2, weak count 0) = {...}, 
    crit=std::shared_ptr<w2l::SequenceCriterion> (use count 2, weak count 0) = {...}, trainset=std::shared_ptr<w2l::W2lDataset> (use count 2, weak count 0) = {...}, 
    netopt=warning: RTTI symbol not found for class 'fl::SGDOptimizer'
..., critopt=warning: RTTI symbol not found for class 'fl::SGDOptimizer'
..., clampCrit=true, nepochs=100) at /home/jay/wav2letter/Train.cpp:448
#14 0x00005555555968cd in main (argc=4, argv=0x7fffffffe1a8) at /home/jay/wav2letter/Train.cpp:551
```

**Comment by jacobkahn** [comment]
Looks like this is the same problem as https://github.com/facebookresearch/wav2letter/issues/127. @jayavanth I'll follow up/investigate there.
