### ISSUE TITLE
Train crashes (segmentation fault)

### ISSUE THREAD

**Issue by hcoolh** [facebookresearch/wav2letter#208]
Hi
When trying to run Train (to train WSJ), I get this error:
```
wav2letter/recipes/wsj$ ../../build/Train train -flagfile configs/conv_glu/train.cfg
*** Aborted at 1550243856 (unix time) try "date -d @1550243856" if you are using GNU date ***
PC: @     0x2b8d2a0f8328 graphics::ForgeManager::~ForgeManager()
*** SIGSEGV (@0x0) received by PID 104862 (TID 0x2b8d021fc4c0) from PID 0; stack trace: ***
    @     0x2b8d069fb0c0 (unknown)
    @     0x2b8d2a0f8328 graphics::ForgeManager::~ForgeManager()
    @     0x2b8d29b88760 std::default_delete<>::operator()()
    @     0x2b8d29b877e7 std::unique_ptr<>::~unique_ptr()
    @     0x2b8d29b83ca7 cuda::DeviceManager::DeviceManager()
    @     0x2b8d29b81bc5 cuda::DeviceManager::getInstance()
    @     0x2b8d29b81c86 cuda::memoryManager()
    @     0x2b8d29b5788e cuda::setMemStepSize()
    @     0x2b8d29e18614 af_set_mem_step_size
    @     0x2b8d2a08af72 af::setMemStepSize()
    @     0x561939f44e6e main
    @     0x2b8d6789f2e1 __libc_start_main
    @     0x561939f8512a _start
    @                0x0 (unknown)
Segmentation fault
```

I have compiled Arrayfire, Flashlight and wav2letter with cuda 9.2. 
Could you please help with this issue? Or should I ask this on Arrayfire's page?
I can also provide a backtrace from gdb if needed.

Thanks

**Comment by jacobkahn** [comment]
@hcoolh — can you run ArrayFire, flashlight, and wav2letter tests and confirm that they all pass? A gdb backtrace would be helpful.

**Comment by hcoolh** [comment]
Arrayfire's test gets stuck here (currently stuck for ~10min):
```
Running tests...
Test project /etc/arrayfire/build
        Start   1: test_anisotropic_diffusion_cpu
  1/244 Test   #1: test_anisotropic_diffusion_cpu ....   Passed    0.25 sec
        Start   2: test_anisotropic_diffusion_cuda
```

And here is the backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00002aaad2a15328 in graphics::ForgeManager::~ForgeManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
(gdb) bt
#0  0x00002aaad2a15328 in graphics::ForgeManager::~ForgeManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#1  0x00002aaad24a5760 in std::default_delete<graphics::ForgeManager>::operator()(graphics::ForgeManager*) const ()
   from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#2  0x00002aaad24a47e7 in std::unique_ptr<graphics::ForgeManager, std::default_delete<graphics::ForgeManager> >::~unique_ptr() ()
   from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#3  0x00002aaad24a0ca7 in cuda::DeviceManager::DeviceManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#4  0x00002aaad249ebc5 in cuda::DeviceManager::getInstance() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#5  0x00002aaad249ec86 in cuda::memoryManager() () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#6  0x00002aaad247488e in cuda::setMemStepSize(unsigned long) () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#7  0x00002aaad2735614 in af_set_mem_step_size () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#8  0x00002aaad29a7f72 in af::setMemStepSize(unsigned long) () from /etc/arrayfire/build/src/backend/cuda/libafcuda.so.3
#9  0x0000555555585e6e in main ()
```

**Comment by jacobkahn** [comment]
@hcoolh — this is an issue with ArrayFire. I'd recommend posting an issue there. Closing here for now.
