### ISSUE TITLE
Error while importing binding in Python3.6

### ISSUE THREAD

**Issue by chintler** [facebookresearch/wav2letter#486]
Hi,

I installed wav2letter, tested the multithreaded_streaming_asr_example and other examples, and I'm now trying to install the python3.6 bindings. After doing some basic changes for Python3.6(print statements) I'm seeing the following issue:

> Traceback (most recent call last):
  File "./examples/decoder_example.py", line 12, in <module>
    from wav2letter.decoder import (
  File "/wav2letter/bindings/python/wav2letter/decoder.py", line 3, in <module>
    from wav2letter._decoder import *
ImportError: /wav2letter/bindings/python/wav2letter/_decoder.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2lm5ngram11LoadVirtualEPKcRKNS0_6ConfigENS0_9ModelTypeE

I have followed[ the instructions](https://github.com/facebookresearch/wav2letter/wiki/Building-Python-bindings). Can someone help?

**Comment by tlikhomanenko** [comment]
Hi @chintler,

we are supporting installation only for python 3.6 and greater, so please use python 3.6 for bindings.

**Comment by chintler** [comment]
Hi, I'm using python 3.6, there was a spelling error in the title.

**Comment by tlikhomanenko** [comment]
@chintler,

could you try to remove wav2letter/build and wav2letter/bindings/python/build and egg link and to install with `pip install -e . again`? Also please send details on cmake version, OS.

**Comment by chintler** [comment]
A. Yes, import wav2letter works
B. I removed all the packages, folders and links, did a git pull again, and set it up again. Seeing the same issue.
C. I installed KenLM by following the relevant section [here](https://medium.com/@shaheenkader/how-to-install-wav2letter-dc94c3b74e97)
D. The installation gave me multiple errors for KENLM paths while doing CMake via setup.py, even after the necessary exports, so I added 
>"-DCMAKE_INCLUDE_PATH="+"<path_to_KenLM>/kenlm",
"-DKENLM_LIB="+"<path_to_KenLM>/kenlm",
"-DKENLM_UTIL_LIB="+"<path_to_KenLM>/kenlm/util",
"-DKENLM_INC="+"<path_to_KenLM>/kenlm/lm"

in the setup.py file to *cmake_args* variable while spawning the CMake command. I could try again without this change to setup.py.  

E. Log of pip install
The directory '<root dir>' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '<root dir>' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining <root dir>/asr/wav2letter/bindings/python
Installing collected packages: wav2letter
  Running setup.py develop for wav2letter
Successfully installed wav2letter-0.0.2
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

E. My OS is Ubuntu 16.04.5LTS, CMake is at 3.5.1

Thank you for your help and sorry for the late reply.

**Comment by tlikhomanenko** [comment]
@chintler 

So the problem that kenlm is not seen correctly during installation, that is why you have this Traceback which is exactly connected to usage of kenlm from the w2l.

Did you run `export KENLM_ROOT_DIR=/root/kenlm` before calling `pip install -e .`? 
Could you try to use the following kenlm installation and then python bindings (don't forget to remove build folder in bindings before)
```
    cd your/path && git clone https://github.com/kpu/kenlm.git && \
    cd kenlm && git checkout e47088ddfae810a5ee4c8a9923b5f8071bed1ae8 && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON && \
    make -j8
   
    export KENLM_ROOT_DIR=your/path/kenlm && cd path/to/wav2letter/bindings/python && \
    pip install -e .
```

**Comment by tlikhomanenko** [comment]
@chintler 

Did you make it work?

**Comment by chintler** [comment]
Hi, I've been getting the same error again, even though the demos for wav2letter work fine for me. I have done a clean install multiple times. Do you have any pointers for debugging?

**Comment by tlikhomanenko** [comment]
Could you send the full log of installation? There is some linking problem during installation and you should see this if you check the log of installation. I cannot reproduce you error. One of the solution if there are still problems - use Docker image, python bindings are also installed there.

**Comment by chintler** [comment]
Hi, I think the log's too long and I'm taking your suggestion for docker image. I wasn't able to resolve the issue in the last week and am willing to close it. Thank you for your help.

**Comment by AVSuni** [comment]
I received the same error and the Dockerfile python bindings installation fails. These are a part of the logs:

`2020-03-20T13:07:32,886     -- Looking for KenLM
2020-03-20T13:07:32,887     -- Using kenlm library found in /root/kenlm
2020-03-20T13:07:32,887     -- Using kenlm utils library found in /root/kenlm
2020-03-20T13:07:32,888     -- kenlm lm/model.hh found in /root/kenlm/lm/model.hh
2020-03-20T13:07:32,892     -- Found kenlm: /root/kenlm
2020-03-20T13:07:32,893     -- Found kenlm (include: /root/kenlm, library: /root/kenlm;/root/kenlm/util)
2020-03-20T13:07:32,897     -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
2020-03-20T13:07:33,017     -- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
2020-03-20T13:07:33,018     -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
2020-03-20T13:07:33,168     -- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
2020-03-20T13:07:33,169     -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
2020-03-20T13:07:33,291     -- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
2020-03-20T13:07:33,296     -- Found LibLZMA: /usr/include (found version "5.2.2")
2020-03-20T13:07:33,311     -- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6")
2020-03-20T13:07:33,314     -- Looking for BZ2_bzCompressInit
2020-03-20T13:07:33,430     -- Looking for BZ2_bzCompressInit - found
2020-03-20T13:07:33,476     -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
2020-03-20T13:07:33,656     -- Found PythonInterp: /miniconda/envs/py36/bin/python (found version "3.6.4")
2020-03-20T13:07:33,694     -- Found PythonLibs: /miniconda/envs/py36/lib/libpython3.6m.so
2020-03-20T13:07:33,707     -- Performing Test HAS_FLTO
2020-03-20T13:07:33,901     -- Performing Test HAS_FLTO - Success
2020-03-20T13:07:33,902     -- LTO enabled
2020-03-20T13:07:33,916     -- Configuring done
2020-03-20T13:07:33,957     WARNING: Target "wav2letter-libraries" requests linking to directory "/root/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:33,958     WARNING: Target "wav2letter-libraries" requests linking to directory "/root/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,006     WARNING: Target "_common" requests linking to directory "/root/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,006     WARNING: Target "_common" requests linking to directory "/root/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,041     WARNING: Target "_criterion" requests linking to directory "/root/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,041     WARNING: Target "_criterion" requests linking to directory "/root/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,074     WARNING: Target "_decoder" requests linking to directory "/root/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,074     WARNING: Target "_decoder" requests linking to directory "/root/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,106     WARNING: Target "_feature" requests linking to directory "/root/kenlm".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,107     WARNING: Target "_feature" requests linking to directory "/root/kenlm/util".  Targets may link only to libraries.  CMake is dropping the item.
2020-03-20T13:07:34,138     -- Generating done
2020-03-20T13:07:34,149     -- Build files have been written to: /root/wav2letter/bindings/python/build/temp.linux-x86_64-3.6
2020-03-20T13:07:34,228     Scanning dependencies of target pybind11
2020-03-20T13:07:34,232     Scanning dependencies of target CUB
2020-03-20T13:07:34,250     [  1%] Creating directories for 'CUB'
2020-03-20T13:07:34,250     [  1%] Creating directories for 'pybind11'
2020-03-20T13:07:34,331     [  1%] Performing download step (git clone) for 'pybind11'
2020-03-20T13:07:34,333     [  2%] Performing download step (git clone) for 'CUB'
2020-03-20T13:07:34,355     Cloning into 'pybind11'...
2020-03-20T13:07:34,360     Cloning into 'CUB'...
2020-03-20T13:07:36,493     Note: checking out '9a19306fbf30642ca331d0ec88e7da54a96860f9'.`

**Comment by AVSuni** [comment]
Also, this is the error from the Dockerfile-inference:
/usr/bin/ld: /root/kenlm/build/lib/libkenlm.a(config.cc.o): relocation R_X86_64_32S against `_ZSt4cerr' can not be used when making a shared object; recompile with -fP
IC
    /root/kenlm/build/lib/libkenlm.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    bindings/python/CMakeFiles/_feature.dir/build.make:833: recipe for target '../../wav2letter/_feature.cpython-36m-x86_64-linux-gnu.so' failed
    make[2]: *** [../../wav2letter/_feature.cpython-36m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:253: recipe for target 'bindings/python/CMakeFiles/_feature.dir/all' failed
    make[1]: *** [bindings/python/CMakeFiles/_feature.dir/all] Error 2
    [100%] Linking CXX shared module ../../../../wav2letter/_decoder.cpython-36m-x86_64-linux-gnu.so
    /usr/bin/ld: /root/kenlm/build/lib/libkenlm.a(config.cc.o): relocation R_X86_64_32S against `_ZSt4cerr' can not be used when making a shared object; recompile with -fP
IC
    /root/kenlm/build/lib/libkenlm.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    bindings/python/CMakeFiles/_decoder.dir/build.make:833: recipe for target '../../wav2letter/_decoder.cpython-36m-x86_64-linux-gnu.so' failed
    make[2]: *** [../../wav2letter/_decoder.cpython-36m-x86_64-linux-gnu.so] Error 1
    CMakeFiles/Makefile2:404: recipe for target 'bindings/python/CMakeFiles/_decoder.dir/all' failed
    make[1]: *** [bindings/python/CMakeFiles/_decoder.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed

**Comment by tlikhomanenko** [comment]
@AVSuni can you point me which docker image are you using? Or you are trying to build by yourself? Which version of Dockerfile are you using to build?

**Comment by AVSuni** [comment]
@tlikhomanenko many thanks. This was with the latest Dockerfile-Inference

**Comment by tlikhomanenko** [comment]
@AVSuni, here my steps I did and everything works for me:

```
sudo docker run --rm -d -it --name test  wav2letter/wav2letter:inference-latest
sudo docker exec -it test bash
```
- inside docker container
```
apt-get update 
apt-get install libopenblas-dev libfftw3-dev liblapacke-dev
cd /root/kenlm/build && cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON && make -j8
export USE_CUDA=0 && export KENLM_ROOT_DIR=/root/kenlm && cd /root/wav2letter/bindings/python && pip install -e .
```
then run python and do 
```
from wav2letter.decoder import KenLM
import wav2letter
```
both imports works for me. Can you try these steps? (also remember to delete `build` and `wav2letter.egg-info` before rerun `pip install -e .` if installation crashed before)

**Comment by AVSuni** [comment]
Many thanks @tlikhomanenko, I can confirm that it works. It must have been due to lack of BLAS and LAPACK.

**Comment by wahyubram82** [comment]
try this step:

```
from wav2letter import decoder
from wav2letter import criterion
from wav2letter import common

CriterionType = decoder.CriterionType
DecoderOptions = decoder.DecoderOptions
KenLM = decoder.KenLM
LexiconDecoder = decoder.LexiconDecoder
SmearingMode = decoder.SmearingMode
Trie = decoder.Trie


CpuViterbiPath = criterion.CpuViterbiPath
get_data_ptr_as_bytes = criterion.get_data_ptr_as_bytes

create_word_dict = common.create_word_dict
load_words = common.load_words
tkn_to_idx = common.tkn_to_idx
```
