### ISSUE TITLE
ASR in Python via wav2letter?

### ISSUE THREAD

**Issue by ML6634** [facebookresearch/wav2letter#546]
It sounds that wav2letter is mainly for C++. May I use Python instead? If so, any Hello World Python ASR sample program which converts a wav file to text using wav2letter? Thank you!

**Comment by tlikhomanenko** [comment]
Hi @ML6634,

We support python bindings for some part of the wav2letter: [how to install](https://github.com/facebookresearch/wav2letter/wiki/Building-Python-bindings) and [python API for what we support](https://github.com/facebookresearch/wav2letter/wiki/Python-bindings). We don't support training in python.

**Comment by vigneshmj1997** [comment]
hi @tlikhomanenko i am getting this error while executing pip install -e .

this was done in cpu docker image provided my wavtoletter and every command was executed till make j8  
'
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-lyw3y7yl/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-lyw3y7yl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6d1w77jg/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/wav2letter
         cwd: /tmp/pip-req-build-lyw3y7yl/
    Complete output (38 lines):
    running install
    running build
    running build_ext
    CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-lyw3y7yl/setup.py", line 109, in <module>
        zip_safe=False,
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-lyw3y7yl/setup.py", line 48, in run
        self.build_extensions()
      File "/tmp/pip-req-build-lyw3y7yl/setup.py", line 88, in build_extensions
        ["cmake", sourcedir] + cmake_args, cwd=self.build_temp, env=env
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-lyw3y7yl/wav2letter', '-DPYTHON_EXECUTABLE=/usr/bin/python3.6', '-DW2L_BUILD_LIBRARIES_ONLY=ON', '-DW2L_BUILD_FOR_PYTHON=ON', '-DW2L_LIBRARIES_USE_CUDA=ON', '-DW2L_LIBRARIES_USE_KENLM=ON', '-DW2L_LIBRARIES_USE_MKL=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-lyw3y7yl/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-lyw3y7yl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-6d1w77jg/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/wav2letter Check the logs for full command output.
'


thankyou in advance

**Comment by tlikhomanenko** [comment]
@vigneshmj1997,

Please have a look my comment in https://github.com/facebookresearch/wav2letter/issues/558 how to install it.
